### ISSUE TITLE
我的点击turn on 一直打不开 默认一直是off？

### ISSUE THREAD

**Issue by JasonBtc** [paradiseduo/Trojan#4]
![1111](https://user-images.githubusercontent.com/4370703/82856120-bebc7800-9f3f-11ea-8fb4-675ca8b0b1a9.jpeg)
![22222](https://user-images.githubusercontent.com/4370703/82856234-08a55e00-9f40-11ea-8fee-59d9b3524053.jpg)

**Comment by JasonBtc** [comment]
是bug吗 version 1.5

**Comment by paradiseduo** [comment]
看一下日志，另外trojan的命令行程序可以在你的电脑上正常运行吗？
```bash
❯ cd /Applications/Trojan.app/Contents/Resources/

❯ ./trojan --version
Welcome to trojan 1.15.1
Boost 1_72, OpenSSL 1.1.1d  10 Sep 2019
[Disabled] MySQL Support
 [Enabled] TCP_FASTOPEN Support
[Disabled] TCP_FASTOPEN_CONNECT Support
 [Enabled] SSL KeyLog Support
[Disabled] NAT Support
 [Enabled] TLS1.3 Ciphersuites Support
[Disabled] TCP Port Reuse Support
OpenSSL Information
	Build Flags: compiler: clang -fPIC -arch x86_64 -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -D_REENTRANT -DNDEBUG
```

**Comment by paradiseduo** [comment]
如果不能用，那么你需要用brew安装一下缺失的库：
```bash
brew tap trojan-gfw/homebrew-trojan
brew install trojan
```

**Comment by JasonBtc** [comment]
已经brew安装了上面两个，运行还是提示这个，并且turn on一直选择不了 还是off状态
![image](https://user-images.githubusercontent.com/4370703/82858966-f7604f80-9f47-11ea-89af-0f24a8eba819.png)

**Comment by JasonBtc** [comment]
感谢大佬的及时回复~

**Comment by paradiseduo** [comment]
那可能要重写这一部分逻辑了，你的日志里面有报错吗？

**Comment by JasonBtc** [comment]
![image](https://user-images.githubusercontent.com/4370703/82859843-6dfe4c80-9f4a-11ea-82e3-6fb0038c6607.png)
根据view logs查看的路径里面，并没有看到log文件，我的系统是10.15.4

**Comment by paradiseduo** [comment]
release 1.6
